### ISSUE TITLE
Can't register identity in multiple namespaces through helm values for v3

### ISSUE THREAD

**Issue by guidola** [Azure/aad-pod-identity#1020]
**Describe the bug**

Because of the nature itself of maps a key cannot be used twice and hence it is not possible to create the same identity in two different namespaces by using the azureIdentities attribute of the helm chart.

```
+ azureIdentities:
+  "azure-identity": # If we attempt to provide multiple with different namespace value only last will get created
+    # if not defined, then the azure identity will be deployed in the same namespace as the chart
+    namespace: "namespace1"
+    # type 0: MSI, type 1: Service Principal
+    type: 0
+    # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
+    resourceID: "resource-id"
+    clientID: "client-id"
+    binding:
+      name: "azure-identity-binding"
+      # The selector will also need to be included in labels for app deployment
+      selector: "demo"
```

**Expected behavior**

One should be able to create an identity for each namespace when working in namespaced identities mode.

One could get back the ability to do so by:

```
 azureIdentities:
  "azure-identity": # If we attempt to provide multiple with different namespace value only last will get created
    # if not defined, then the azure identity will be deployed in the same namespace as the chart
-   namespace:
+   namespaces: 
+    - namespace1
+    - namespace2
    # type 0: MSI, type 1: Service Principal
    type: 0
    # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
    resourceID: "resource-id"
    clientID: "client-id"
    binding:
      name: "azure-identity-binding"
      # The selector will also need to be included in labels for app deployment
      selector: "demo"
```

or:

```
 azureIdentities:
  "azure-identity-namespace1": 
    # if not defined, then the azure identity will be deployed in the same namespace as the chart
    namespace: "namespace1"
+   name: "azure-identity" # We can optionally provide the name of the identity as a parameter. Defalt will take the key as name
    # type 0: MSI, type 1: Service Principal
    type: 0
    # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
    resourceID: "resource-id"
    clientID: "client-id"
    binding:
      name: "azure-identity-binding"
      # The selector will also need to be included in labels for app deployment
      selector: "demo"
```

**AAD Pod Identity version**
1.7.4
**Kubernetes version**
1.20.2
**Additional context**
