### ISSUE TITLE
Nmi can not be scheduled on AKS nodespot

### ISSUE THREAD

**Issue by calvinShan** [Azure/aad-pod-identity#1042]
**Describe the bug**
We have deployed NMI on our AKS cluster.
The auth processus works well in the pods on the nodes.
kubectl -n data exec -it pod/test-vincent2 -- curl -i -H "Metadata: true" -X GET "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2020-06-01&resource=https://storage.azure.com"
retour code: 200 

However, when we want to run this command in the Pod that scheduled on AKS nodespot, it doesn't work
kubectl -n data exec -it pod/test-vincent2 -- curl -i -H "Metadata: true" -X GET "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2020-06-01&resource=https://storage.azure.com"
retour code: 400

I have checked that nmi pod is scheduled in every node besides nodespot, and i think that is the problem. 

And I have deployed another daemoset, which create pod in every node **except** nodespot

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
      matchLabels:
        name: fluentd # Label selector that determines which Pods belong to the DaemonSet
  template:
    metadata:
      labels:
        name: fluentd # Pod template's label selector
    spec:
      containers:
      - name: fluentd
        image: gcr.io/google-containers/fluentd-elasticsearch:1.20
```
It can't schedule pod in Node**Spot** on AKS
**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
nmi: 1.6.1

**Kubernetes version**
aks: 1.19.7
