### ISSUE TITLE
Multiple user assigned identities exist

### ISSUE THREAD

**Issue by michaeljguarino** [Azure/aad-pod-identity#1059]
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
On a fresh cluster using managed identities, the MIC cannot bootstrap itself due to an error like:

```
failed to get vmss <vmss-name in resource group <rg-name>, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subId>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachineScaleSets/<vmss-name>?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
```

**Steps To Reproduce**
Create AKS cluster using managed identity, install aad-pod-identity helm chart with values like:

```
adminsecret:
      clientID: msi
      clientSecret: msi
      cloud: AzurePublicCloud
      resourceGroup: <<rg-name>>
      subscriptionID: <<subscription-id>>
      tenantID: <<tenant-id>>
      useMSI: "true"
      userAssignedMSIClientID: <<user-assigned-client-id>> # mine looks like a uuid
      vmType: vmss
```

**Expected behavior**
MIC works and spits out now error messages

**AAD Pod Identity version**
latest helm chart

**Kubernetes version**
1.20.5

**Additional context**
