### ISSUE TITLE
Error : no azure identity found for request client id

### ISSUE THREAD

**Issue by sent736** [Azure/aad-pod-identity#1074]
Hello,

 We are trying to setup pod identity on our cluster to enable accessing Azure services, but the nmi says unable to find the corresponding client id.

We checked the pod identity and its correctly mapped to the client id which has the required access and also the vmss is assigned with the identity. 

We are new to this set up and  Any help would be greatly appreciated? 

Thanks
Sen

**Comment by chewong** [comment]
Could you provide MIC and NMI logs?

**Comment by Konnor5092** [comment]
I'm experiencing a similar problem.

I went through the following [guide](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity), attempting to follow the flow for Kubenet. I didn't perform any mitigation - I just want to see it working first.

The error from my pod that is attempting to use a managed identity is..
```
 ---> Azure.RequestFailedException: Service request failed.
Status: 404 (Not Found)

Content:
no azure identity found for request clientID
```
My nmi logs have the following repeated
```
E0529 02:06:50.232742       1 server.go:375] failed to get matching identities for pod: default/dep-oconnorevents-eventcatalog-f69c898df-mxzfq, error: no azure identity found for request clientID
I0529 02:06:50.232790       1 server.go:196] status (404) took 166102 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.0.41
```
Neither of these commands return anything for me
```
kubectl logs -l component=mic --since=1h | grep ^E
kubectl logs -l component=nmi --since=1h | grep ^E
```
How do I see MIC logs? This is what I have in my `kube-system` namespace
```
NAME                                  READY   STATUS    RESTARTS   AGE
azure-ip-masq-agent-5clvs             1/1     Running   0          7d18h
coredns-76c97c8599-87cwq              1/1     Running   0          7d18h
coredns-76c97c8599-j9dcv              1/1     Running   0          7d18h
coredns-autoscaler-599949fd86-gqstb   1/1     Running   0          7d18h
kube-proxy-zng69                      1/1     Running   0          7d18h
metrics-server-77c8679d7d-pnsvf       1/1     Running   0          7d18h
nmi-57b2z                             1/1     Running   0          3d16h
omsagent-ps299                        1/1     Running   0          7d18h
omsagent-rs-76b6f67dcc-7wjpw          1/1     Running   0          7d18h
tunnelfront-6cdc8f669b-sqw7s          1/1     Running   0          7d18h
```
If I do a `az aks pod-identity list -g $RESOURCE_GROUP --cluster-name $CLUSTER_NAME` I see the following...

```
{
  "aadProfile": null,
  "addonProfiles": {
    "azurepolicy": {
      "config": null,
      "enabled": false,
      "identity": null
    },
    "httpApplicationRouting": {
      "config": null,
      "enabled": false,
      "identity": null
    },
    "omsAgent": {
      "config": {
        "logAnalyticsWorkspaceResourceID": "/subscriptions/7b73e02c-dbff-4eb7-9d73-e73a2a17e818/resourceGroups/DefaultResourceGroup-SUK/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-7b73e02c-dbff-4eb7-9d73-e73a2a17e818-SUK"
      },
      "enabled": true,
      "identity": {
        "clientId": "02ae36f7-817e-4454-83a1-1a9bc7a31cf2",
        "objectId": "4c62273a-19f4-4720-b209-d6898d01ec3f",
        "resourceId": "/subscriptions/7b73e02c-dbff-4eb7-9d73-e73a2a17e818/resourcegroups/MC_OconnorEvents_OconnorEvents_uksouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent-oconnorevents"
      }
    }
  },
  "agentPoolProfiles": [
    {
      "availabilityZones": [
        "1",
        "2",
        "3"
      ],
      "count": 1,
      "enableAutoScaling": null,
      "enableEncryptionAtHost": null,
      "enableFips": false,
      "enableNodePublicIp": null,
      "gpuInstanceProfile": null,
      "kubeletConfig": null,
      "kubeletDiskType": "OS",
      "linuxOsConfig": null,
      "maxCount": null,
      "maxPods": 110,
      "minCount": null,
      "mode": "System",
      "name": "agentpool",
      "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2021.05.08",
      "nodeLabels": {},
      "nodePublicIpPrefixId": null,
      "nodeTaints": null,
      "orchestratorVersion": "1.19.9",
      "osDiskSizeGb": 128,
      "osDiskType": "Managed",
      "osSku": "Ubuntu",
      "osType": "Linux",
      "podSubnetId": null,
      "powerState": {
        "code": "Running"
      },
      "provisioningState": "Succeeded",
      "proximityPlacementGroupId": null,
      "scaleSetEvictionPolicy": null,
      "scaleSetPriority": null,
      "spotMaxPrice": null,
      "tags": null,
      "type": "VirtualMachineScaleSets",
      "upgradeSettings": null,
      "vmSize": "Standard_B2s"
    }
  ],
  "apiServerAccessProfile": {
    "authorizedIpRanges": null,
    "enablePrivateCluster": false,
    "privateDnsZone": null
  },
  "autoScalerProfile": null,
  "autoUpgradeProfile": null,
  "azurePortalFqdn": "oconnorevents-dns-2b2d7724.portal.hcp.uksouth.azmk8s.io",
  "disableLocalAccounts": null,
  "diskEncryptionSetId": null,
  "dnsPrefix": "OconnorEvents-dns",
  "enablePodSecurityPolicy": null,
  "enableRbac": true,
  "extendedLocation": null,
  "fqdn": "oconnorevents-dns-2b2d7724.hcp.uksouth.azmk8s.io",
  "fqdnSubdomain": null,
  "httpProxyConfig": null,
  "id": "/subscriptions/7b73e02c-dbff-4eb7-9d73-e73a2a17e818/resourcegroups/OconnorEvents/providers/Microsoft.ContainerService/managedClusters/OconnorEvents",
  "identity": {
    "principalId": "d7777e45-e4b8-425b-a2cb-90c7156c5193",
    "tenantId": "792d99aa-3678-46e8-aa18-e28e97443aee",
    "type": "SystemAssigned",
    "userAssignedIdentities": null
  },
  "identityProfile": {
    "kubeletidentity": {
      "clientId": "c47ed2b0-af56-47d2-8141-777ff6f08d01",
      "objectId": "78491c0e-8194-425f-b6c3-6e8167b5d196",
      "resourceId": "/subscriptions/7b73e02c-dbff-4eb7-9d73-e73a2a17e818/resourcegroups/MC_OconnorEvents_OconnorEvents_uksouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/OconnorEvents-agentpool"
    }
  },
  "kubernetesVersion": "1.19.9",
  "linuxProfile": null,
  "location": "uksouth",
  "maxAgentPools": 100,
  "name": "OconnorEvents",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "loadBalancerProfile": {
      "allocatedOutboundPorts": null,
      "effectiveOutboundIps": [
        {
          "id": "/subscriptions/7b73e02c-dbff-4eb7-9d73-e73a2a17e818/resourceGroups/MC_OconnorEvents_OconnorEvents_uksouth/providers/Microsoft.Network/publicIPAddresses/2e4d31a7-8666-4031-b2a9-a03494fefbb1",
          "resourceGroup": "MC_OconnorEvents_OconnorEvents_uksouth"
        }
      ],
      "idleTimeoutInMinutes": null,
      "managedOutboundIps": {
        "count": 1
      },
      "outboundIpPrefixes": null,
      "outboundIps": null
    },
    "loadBalancerSku": "Standard",
    "networkMode": null,
    "networkPlugin": "kubenet",
    "networkPolicy": null,
    "outboundType": "loadBalancer",
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "MC_OconnorEvents_OconnorEvents_uksouth",
  "podIdentityProfile": {
    "allowNetworkPluginKubenet": true,
    "enabled": true,
    "userAssignedIdentities": [
      {
        "bindingSelector": null,
        "identity": {
          "clientId": "c13e95dd-f733-4940-b4e1-456e328a758f",
          "objectId": "c2453c4f-9509-44cb-9226-4e93e6270ab4",
          "resourceId": "/subscriptions/7b73e02c-dbff-4eb7-9d73-e73a2a17e818/resourcegroups/OconnorEvents/providers/Microsoft.ManagedIdentity/userAssignedIdentities/oconnorevents-identity"
        },
        "name": "pod-identity",
        "namespace": "default",
        "provisioningInfo": null,
        "provisioningState": "Assigned"
      }
    ],
    "userAssignedIdentityExceptions": null
  },
  "powerState": {
    "code": "Running"
  },
  "privateFqdn": null,
  "privateLinkResources": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "OconnorEvents",
  "servicePrincipalProfile": {
    "clientId": "msi"
  },
  "sku": {
    "name": "Basic",
    "tier": "Free"
  },
  "type": "Microsoft.ContainerService/ManagedClusters",
  "windowsProfile": null
}
```
In my deployment file I have the following...

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-oconnorevents-eventcatalog
  labels:
    aadpodidbinding: pod-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oconnorevents-eventcatalog
  template:
    metadata:
      labels:
        app: oconnorevents-eventcatalog
    spec:
      containers:
      - name: oconnorevents-eventcatalog
        image: oconnoreventsme.azurecr.io/oconnoreventseventcatalog:#{Build.BuildId}#
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__DefaultConnection
          valueFrom: 
            secretKeyRef:
              name: eventcatalog-db
              key: connectionstring
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: acr-secret
```
And finally in my code I have the following
```csharp
if (env.IsProduction())
{
    var settings = configurationBuilder.Build();
    configurationBuilder.AddAzureAppConfiguration(options =>
        options.Connect(new Uri(settings["AppConfig:Endpoint"]), new ManagedIdentityCredential()));
}
```
Running the test pod with the following worked for me
```
kubectl run azure-cli -it --image=mcr.microsoft.com/azure-cli --labels=aadpodidbinding=pod-identity /bin/bash

az login --identity --allow-no-subscriptions --debug
```
```json
[
  {
    "environmentName": "AzureCloud",
    "homeTenantId": "792d99aa-3678-46e8-aa18-e28e97443aee",
    "id": "7b73e02c-dbff-4eb7-9d73-e73a2a17e818",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Matt local subscription",
    "state": "Enabled",
    "tenantId": "792d99aa-3678-46e8-aa18-e28e97443aee",
    "user": {
      "assignedIdentityInfo": "MSI",
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]
```

Where am I going wrong?

**Comment by chewong** [comment]
Sorry for the delayed response. It looks like you will need to add the `aadpodidbinding` in your podspec. See [this](https://azure.github.io/aad-pod-identity/docs/best-practices/#deploymenthttpskubernetesiodocsconceptsworkloadscontrollersdeployment) for more details.

**Comment by StevenTCramer** [comment]
You have the aadpodidbinding label on the deployment and you need it on the spec.  (Not that I just had the same problem :)
You have:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-oconnorevents-eventcatalog
  labels:
    aadpodidbinding: pod-identity # <====  should not be here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oconnorevents-eventcatalog
  template:
    metadata:
      labels:
        # <======== move the aadpodidbinding label to here
        app: oconnorevents-eventcatalog
...
```
