### ISSUE TITLE
Multiple assigned identities issue

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/aad-pod-identity#1077]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Hello. I am trying to make cermanager work with AzureDNS using DNS01 challenge. My AKS cluster is deployed with MSI enabled. AAD pod identity is deployed in the managed mode and forced namespaces. AzureIdentity and AzureIdentityBinding are created, certmanager pod is deployed with a correct label and in the same namespace. When I try to create a certificate, it fails with the next issue:
``` 
I0524 08:32:07.905501       1 server.go:302] fetching token for system assigned MSI
E0524 08:32:07.966448       1 server.go:365] failed to get service principal token for pod:security/security-ops-certmanager-867887fdd4-5pbs9 with error code 403, error: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
```
VMss nodes have multiple identities assigned, but I assume that AzureIdentityBinding should make only one identity available for pod, is that correct?

**AAD Pod Identity version**
helm 4.1.1 (1.8.0)
**Kubernetes version**
1.19.9

**Comment by aramase** [comment]
Is the pod `security/security-ops-certmanager-867887fdd4-5pbs9` excepted using `AzurePodIdentityException`? https://azure.github.io/aad-pod-identity/docs/configure/application_exception/

The client token request is forwarded as is when the client pod is excepted using the `AzurePodIdentityException`. In that scenario, the client needs to pass the clientID as part of token request. If the pod isn't excepted, then NMI component will default the clientID to the first `AzureIdentity` matched for the pod in the namespace.

**Comment by IvanovOleg** [comment]
@aramase There is no exception for that pod. Only one identity is bound to that pod.
```
certmanager:
  enabled: true
  installCRDs: true
  clusterResourceNamespace: security
  serviceAccount: 
    name: "cert-manager"
  cainjector:
    serviceAccount: 
      name: "cert-manager-cainjector"
    podLabels:
      aadpodidbinding: certman-identity
  webhook:
    serviceAccount:
      name: "cert-manager-webhook"
    podLabels:
      aadpodidbinding: certman-identity
  podLabels:
    aadpodidbinding: certman-identity
```
```
aad-pod-identity:
  operationMode: managed
  forceNamespaced: true
  azureIdentities:
    certman-identity:
      type: 0
      resourceID: /subscriptions/***/resourceGroups/***/providers/Microsoft.ManagedIdentity/userAssignedIdentities/***
      clientID: ***
      binding:
        name: certman-identity-binding
        selector: certman-identity
```
