### ISSUE TITLE
invalid resource id:  must match /subscriptions/<subid>/resourcegroups/

### ISSUE THREAD

**Issue by Yiyito11** [Azure/aad-pod-identity#1088]
**Describe the bug**

After I created nmi and mic pods , installed AzureIdentity, AGIC chart and AzureIdentityBinding

I´m getting 0/1 in ingress pod. So when checking the logs in MIC pods, I´m getting:

`E0604 20:11:23.119775       1 mic.go:946] ignoring azure identity default/aks-identitypod, error: invalid resource id: "subscriptions/75fxxxxxxxxxxxxxx/resourcgroups/MC_RG_RGGGGG_centralus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/USCDFSOSF2MNI01", **must match /subscriptions/<subid>/resourcegroups/<resourcegroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<name>**`

**Steps To Reproduce**

Installed nmi and mic pods with:

`kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.6.0/deploy/infra/deployment-rbac.yaml`
Created AzureIdentity

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity

metadata:
  name: aks-identity-central 

spec:
  type: 0
  resourceID: subscriptions/75fxxxxxxxxxxxxxx/resourcgroups/MC_RG_RGGGGG_centralus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/USCDFSOSF2MNI01
  clientID: 75cd6fba-xxxxxxxxxxxxxxxxxxxx
```
Tried with  **_resourcgroups and resourcGroups_**

Installed Helm Chart:

```
# This file contains the essential configs for the ingress controller helm chart

# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 3

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: 75fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    resourceGroup: USxxxxxxxxxxxxxxxx
    name: Uxxxxxxxxxxxxxxx
    usePrivateIP: false

    # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
    # This prohibits AGIC from applying config for any host/path.
    # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
    shared: false

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
# Leaving this variable out or setting it to blank or empty string would
# result in Ingress Controller observing all acessible namespaces.
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
armAuth:
    type: aadPodIdentity
    identityResourceID: subscriptions/75fxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourcGroups/MC_RG_RGGGGG_centralus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/USCDFSOSF2MNI01
    identityClientID:  75cd6fbaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## Alternatively you can use Service Principal credentials
# armAuth:
#    type: servicePrincipal
#    secretJSON: <<Generate this value with: "az ad sp create-for-rbac --subscription <subscription-uuid> --sdk-auth | base64 -w0" >>

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
    enabled: true # true/false
```

Installed AzureIdentityBinding

```
# aadpodidentitybinding.yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding

metadata:
  name: aks-identity-central

spec:
  azureIdentity: aks-identitypod-central
  selector: ingress-azure-1622837715 #Here the name I got after ingress was created
```

**Expected behavior**

igress pod running 1/1. Now I´m getting 0/1

ingres logs:

```
k logs ingress-azure-1622837715-69c58fc869-7r2fb
I0604 20:41:42.282723       1 utils.go:115] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0604 20:41:42.326292       1 environment.go:248] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0604 20:41:42.326319       1 main.go:117] Using User Agent Suffix='ingress-azure-1622837715-69c58fc869-7r2fb' when communicating with ARM
I0604 20:41:42.326448       1 main.go:136] Appication Gateway Details: Subscription="75fabbb8-6172-46e7-a44c-bcf1ea6f0803" Resource Group="USCPFSOSF2RSG02" Name="USCDFSOSF2AAG01"
I0604 20:41:42.326469       1 auth.go:46] Creating authorizer from Azure Managed Service Identity
I0604 20:41:42.326529       1 httpserver.go:57] Starting API Server on :8123
```

**AAD Pod Identity version**

tied first with v1.8.0 then removed and tried with v1.7.0

**Kubernetes version**

1.19.9

**Additional context**

first time I run into this issue. Generally it´s pretty straight forward the AGIC Brownfield deployment.

I noticed that error   says : "must match /subscriptions/<subid>/**resourcegroups**/<resourcegroup"  so I changed it to lowercase since in Azure portal its : `resourceGroups`

Is the first time I´m getting this type of error. Path of : `/subscriptions/<subid>/resourcegroups/<resourcegroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<name`> matches exactly with the one I Provided in AzureIdentity

AzureIdentity rseource ID and clientID matches the same as the helm chart. And the ManagedIdentity is created ok and assigned as contributor in RG of Appgateway and reader in the Appgateway RG.
