### ISSUE TITLE
[helm]: Make azureIdentities.identity.binding optional 

### ISSUE THREAD

**Issue by Segflow** [Azure/aad-pod-identity#1142]
**Describe the bug**

We want to be build to define some azure identities when creating the helm chart but without defining any binding.

Currently this fails with:

```
Error: template: aad-pod-identity/templates/identities.yaml:29:21: executing "aad-pod-identity/templates/identities.yaml" at <$value.binding.name>: nil pointer evaluating interface {}.name
```

**Steps To Reproduce**

Use this `values.yaml`

```yaml
azureIdentities:
  testid:
    name: "testid_name"
    namespace: "namespaceA"
    type: 0
    resourceID: "12"
    clientID: "12"

```

**Expected behavior**

When no binding is defined, only the `AzureIdentity` resources should be created

**AAD Pod Identity version**
1.8.2

**Kubernetes version**
v1.20.7
