### ISSUE TITLE
Proposed Behavior Change: Identity/Namespaces/Assignment

### ISSUE THREAD

**Issue by khenidak** [Azure/aad-pod-identity#115]
Ref: #106 #45 and other

Today, Identities are hardcoded to default namespace. and pods are matched using selector irrespective of `pod.namespace`. The is causing the following:
1. Users would like to compartmentalize application resources at the namespace level. This includes the identity.
2. This model currently does not allow matching `identity.namespace == pod.namespace` 

**Proposed change**:

1. Remove the hardcoded selector in https://github.com/Azure/aad-pod-identity/blob/master/pkg/crd/crd.go#L128 (along with any reference to default namespace in `listXXX` calls)
2. Add annotation to `azureIdentity` to force matching to current namespace only. i.e `true = (pod.namespace == azureIdentity.namespace)` When the annotation is not found then we match in any namespace.

@kkmsft @rite2nikhil @ritazh Thoughts?

**Comment by rite2nikhil** [comment]
The default is to match on any namespace, we will be backward compatible /lgtm

**Comment by brantb** [comment]
Out of curiosity, what is the motivation behind selecting pods based on the label `aadpodidbinding` instead of allowing arbitrary label selectors [as described by the k8s documentation?](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) Typically a namespaced resource will typically reference either (a) other resources in the same namespace, or (b) a non-namespaced resource like a `ClusterRole` or a `PersistentVolume`.

I'd like to suggest the following behavior:

1. Allow `AzureIdentity` and `AzureIdentityBinding` to be placed in any namespace.
2. [breaking] Change the spec of `AzureIdentityBinding` to reference pods in the current namespace using an arbitrary selector, e.g.
```yaml
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: demo-azure-id-binding
  namespace: my-namespace
spec:
  AzureIdentity: my-azure-identity-name
  selector:
    matchLabels:
      app: myapplication # example
      environment: dev   # example
```
3. [breaking] When an `AzureIdentityBinding` references an `AzureIdentity` by name in `spec.AzureIdentity`, match only in the same namespace. (Alternate but also breaking idea: Make `AzureIdentity` a cluster-wide resource so that they do not reside in any namespace)

I completely understand if you don't want to make breaking changes at this time, but this would bring aad-pod-identity more in line with how I've seen many other Kubernetes applications operate.
