### ISSUE TITLE
Egress network policy blocks request to IMDS endpoint

### ISSUE THREAD

**Issue by Holger-Seemueller** [Azure/aad-pod-identity#1195]
Hello everyone,

i have a pod using a pod identity to access an Azure resource. This pod is proteced by a network policy:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-service-policy
spec:
  podSelector:
    matchLabels:
      name: my-service
  egress:
    # allow all egress traffic to cluster's subnet and IMDS endpoint
    - to:
      - ipBlock:
          cidr: 10.6.0.0/17
      - ipBlock:
          cidr: 169.254.169.254/32
```

When the pod is scheduled the contained Spring Boot service throws an exception:
```[...] Caused by: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Connect timed out. [...]```

When i allow all egress traffic via

```
egress:
    - to: {}
```

the container starts successfully and i can use the managed identity as excepted.

So, can anyone tell me which rules do I have to define in order to be able to use aad-pod-identity without allowing all egress traffic?

Kubernetes v1.20
AAD Pod Identity version 1.8.4

Thank you
Holger

**Comment by Tolsto** [comment]
You have to allow egress to 127.0.0.1, 169.254.169.254 is not requires as aad-pod-identity does DNAT to 127.0.0.1.

This Calico GlobalNetworkPolicy does the trick

```
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-imds-access
spec:
  selector: has(aadpodidbinding)
  egress:
    - action: Allow
      destination:
        nets:
          - 127.0.0.1
      protocol: TCP
```
