### ISSUE TITLE
rpc error: code =   Unknown desc = failed to mount secrets store objects for pod   XXX, err: rpc error: code = Unknown desc =   failed to mount objects, error: failed to get keyvault client: failed to get   key vault token: nmi response failed with status code: 404

### ISSUE THREAD

**Issue by MouniR-123** [Azure/aad-pod-identity#1210]
CSI Driver Volume Implimentation:
@aramase @chewong  Hi, I have used helm to install pod identity. mic and nmi pods are running in default namespace , application pod and azureidentity/azureidentitybindings were deployed  in "test" namespace.  application pod status is in "containercreating" state.

NMI pod logs :
```
failed to get identities, error: getting assigned identities for pod XXX in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
1 server.go:199] status (404) took 80031309545 ns for req.method=GET reg.path=/host/token/ req.remote
```
---------------------------------

and I don't see any error messages in mic pod logs.

MIC pod logs: 
```
1 main.go:114] starting mic process. Version: v1.8.5. Build date: 
1 main.go:119] --kubeconfig not passed will use InClusterConfig
main.go:136] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
1 main.go:144] running MIC in namespaced mode: false
1 main.go:148] client QPS set to: 5. Burst to: 5
1 mic.go:138] starting to create the pod identity client. Version: v1.8.5. Build date: 
1 mic.go:144] Kubernetes server version: v1.20.7
1 cloudprovider.go:122] MIC using user assigned identity: XX REDACTED #####XX for authentication.
1 probes.go:41] initialized health probe on port XX
1 probes.go:44] started health probe
1 metrics.go:341] registered views for metric
1 prometheus_exporter.go:21] starting Prometheus exporter
1 metrics.go:347] registered and exported metrics on port XX
1 mic.go:242] initiating MIC Leader election
1 leaderelection.go:248] attempting to acquire leader lease default/aad-pod-identity-mic...
1 leaderelection.go:258] successfully acquired lease default/aad-pod-identity-mic
1 mic.go:330] type upgrade status configmap found from version: v1.8.5. Skipping type upgrade!
1 crd.go:457] CRD informers started
1 pod.go:72] pod cache synchronized. Took 642.476664ms
1 pod.go:79] pod watcher started !!
1 mic.go:400] sync thread started.
```

and azureidentity and azureidentitybindings files:
```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: "managedidentityname"
  namespace: "test"
spec:
  type: 0                                 
  resourceID: XXX
  clientID: XXX
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azurepodidentitybinding
  namespace: "test"
spec:
  azureIdentity: "managedidentityname"      
  selector: "managedidentityname"
```

 not sure what's missing, appreciate your suggestions. Thank you!
