### ISSUE TITLE
Document steps for configuring pod identity with sp + certificate

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#1272]
Steps:

1. Create a service principal with certificate `az ad sp create-for-rbac --create-cert`
2. Convert the PEM file to PKCS12 and set a password
```bash
openssl pkcs12 -export -in /Users/anishramasekar/tmpgmho48ce.pem -out ad-sp-cert.pfx -passout pass:12345
```
3. Create a k8s secret with the certificate and password
```bash
kubectl create secret generic spcreds --from-file=certificate=ad-sp-cert.pfx --from-literal=password=12345
```
4. Create an AzureIdentity and AzureIdentityBinding referencing that secret
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: demo-aad1
spec:
  type: 2
  tenantID: $AZURE_TENANT_ID
  clientID: $AZURE_CLIENT_ID
  clientPassword: {"name":"spcreds","namespace":"default"}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azidbinding0
spec:
  azureIdentity: demo-aad1
  selector: demo-aad1
```

cc @CecileRobertMichon
