### ISSUE TITLE
Application with identifier 'msi' was not found in the directory

### ISSUE THREAD

**Issue by felfa01** [Azure/aad-pod-identity#1277]
I am trying to use my own MSI for aad-pod-identity instead of the auto-generated kubelet MSI XXX-aks-agentpool. I have tried manually assigning my own MSI to the underlying VMSS nodes, but I am facing issues as can be seen in log:

`Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'msi' was not found in the directory '<TENANT_NAME_REDACTED>'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: dc8eca30-deda-4116-9334-2c5e07035c00\r\nCorrelation ID: bfafa912-08d9-43b5-89e1-cc6203f2ef6b\r\nTimestamp: 2022-05-05 06:51:05Z","error_codes":[700016],"timestamp":"2022-05-05 06:51:05Z","trace_id":"dc8eca30-deda-4116-9334-2c5e07035c00","correlation_id":"bfafa912-08d9-43b5-89e1-cc6203f2ef6b","error_uri":"https://login.microsoftonline.com/error?code=700016"}`

My helm values file looks like this:
```yaml
adminsecret:
   cloud: AzurePublicCloud
   subscriptionID: <subscription id>
   resourceGroup: <MC_AKS_RG>
   vmType: vmss
   tenantID: <TENANT_ID>
   clientID: msi
   clientSecret: msi
   useMSI: true
   userAssignedMSIClientID: <MSI_ID>
```

**Comment by aramase** [comment]
@felfa01 Thanks for reporting the issue!

Which version of the helm charts are you using?

From the logs, it looks like MIC is using service principal which makes me think `useMSI` is coming out incorrectly. `useMSI` in the helm chart values needs to be a string. I tried the following values file and it worked fine for me:

```
adminsecret:
   cloud: AzurePublicCloud
   subscriptionID: sub-id
   resourceGroup: MC_myResourceGroup_aks_southcentralus
   vmType: vmss
   tenantID: tenant-id
   clientID: msi
   clientSecret: msi
   useMSI: "true"
   userAssignedMSIClientID: client-id
```

Just setting `useMSI: true` errors out during `helm install` because the value is expected to be a string and not bool
```bash
Error: INSTALLATION FAILED: template: aad-pod-identity/templates/mic-secret.yaml:19:42: executing "aad-pod-identity/templates/mic-secret.yaml" at <b64enc>: wrong type for value; expected string; got bool
```
