### ISSUE TITLE
AzureIdentity and AzureIdentityBinding are randomly deleted

### ISSUE THREAD

**Issue by andre-lx** [Azure/aad-pod-identity#1313]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

We use AzureIdentity and AzureIdentityBinding in three services. 

They work pretty fine, but after some time ALL the AzureIdentity and AzureIdentityBinding are deleted from the cluster for some reason. 

We are facing this from at least kubernetes version 1.19, and the only way we found to solve this is to have a cronjob that recreates the AzureIdentity and AzureIdentityBinding every 1 hour. 

When the binding and the identity are deleted, we can see the mic logs as:

`
No AzureIdentityBinding found for pod default/some-pod-6c5b5d757c-x7t4s that matches selector: some-pod-identity. it will be ignored
`

**Steps To Reproduce**

As an example we have the AzureIdentity and AzureIdentityBinding like this:

```yaml
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: some-pod-identity
spec:
  clientID: -----
  resourceID: /subscriptions/-----/resourceGroups/-----/providers/Microsoft.ManagedIdentity/userAssignedIdentities/-----
  type: 0
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: some-pod-identity-binding
spec:
  azureIdentity: some-pod-identity
  selector: some-pod-identity
```

And the pod like this:

```yaml
apiVersion: v1
kind: Pod
metadata: 
  name: some-0
  labels:
    aadpodidbinding: some-pod-identity
```

**Expected behavior**

**AAD Pod Identity version**

From at least version: 1.8.5

**Kubernetes version**

From at least version: 1.19

**Additional context**

Thanks, André
