### ISSUE TITLE
Failures when getting token for MSI

### ISSUE THREAD

**Issue by zivusomer** [Azure/aad-pod-identity#1360]
My team uses MSI for our authorization when accessing our ~50 storage accounts. We consistently see (in all of them) a steady flow of failures, caused by failure to receive a token.
The exceptions we receive are usually one of the following:

- CredentialUnavailableError at ManagedIdentityCredential.getToken
- AuthenticationError at ManagedIdentityCredential.getToken

The vast majority of the requests succeed, but this is still disturbing.

The Managed Service Identity team in Azure took a look at this and referred me to this channel. When they looked at their logs for the status code returned by the IMDS token request with the following query:
```
let startTime = datetime("2022-11-14 20:00:00");
let endTime = startTime + 2h;
cluster("AzCore.centralus.kusto.windows.net").database("SharedWorkspace").ImdsApiRequests()
| where TIMESTAMP between (startTime..endTime)
| where Url == "/metadata/identity/oauth2/token"
| where Container in <list of guids>
| summarize count() by StatusCode
```
The results were as following:
![image](https://user-images.githubusercontent.com/38352493/201905551-2bd4bf96-7cc4-4802-9be8-d158cac41eea.png)

This is our MSI definition:
```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: draftprodidentity
spec:
  type: 0
  resourceID: /subscriptions/a5dacf5a-7bbe-4000-94cd-f532d42936c4/resourceGroups/draftProd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/draftprodidentity
  clientID: 636848d8-b227-47f9-b2c0-f699144535e3
---  
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: draftprodidentity-binding
spec:
  azureIdentity: draftprodidentity
  selector: draftprodidentity
```

What can we do to eliminate these result codes?
