### ISSUE TITLE
no AzureAssignedIdentity found for pod

### ISSUE THREAD

**Issue by jaijitendra** [Azure/aad-pod-identity#175]
I have been following this article: 
https://github.com/simonness/aad-pod-identity 
But somehow my pods have no azure identitty

Here are my yamls

aadpodidentity.yaml

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: demo-aad1
spec:
 type: 0
 ResourceID: "/subscriptions/<SubscriptionId>/resourceGroups/RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<managedIdentity>" #<Resource ID of Managed Identity>
 ClientID: <clientId> #<Client ID of Managed Identity>
```

aadpodidentitybinding.yaml

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: demo-azure-id-binding
spec:
 AzureIdentity: demo-aad1
 Selector: demo-kv-access 
```

App.yaml
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: jrathor-aspnet
    aadpodidbinding: demo-kv-access
  name: jrathor-aspnet
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: jrathor-aspnet
        aadpodidbinding: demo-kv-access
    spec:
      containers:
      - name: jrathorimg-container
        image: jrathoracr.azurecr.io/jrathorimg:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: jrathoracr-cred
---
apiVersion: v1
kind: Service
metadata:
  name: jrathor-aspnet-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: jrathor-aspnet
```

Here is the output I get when I execute below commands:
```
$ kubectl get AzureIdentity --all-namespaces
NAMESPACE   NAME                  AGE
default     demo-aad1             11h

$ kubectl get AzureIdentityBinding --all-namespaces
NAMESPACE   NAME                          AGE
default     demo-azure-id-binding         23s

$ kubectl get AzureAssignedIdentities --all-namespaces
No resources found.

$ kubectl exec jrathor-aspnet-848d65d575-z6lsl -it sh
# curl  http://169.254.169.254/metadata/identity/oauth2/token/?resource=https://vault.azure.net
no AzureAssignedIdentity found for pod:default/jrathor-aspnet-848d65d575-z6lsl

```
