### ISSUE TITLE
 Failed to list *v1.AzureIdentity error in mic logs when using helm scripts.

### ISSUE THREAD

**Issue by jaijitendra** [Azure/aad-pod-identity#177]
I took the helm charts from https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity and updated values.yaml.

```
# Default values for pod-aad-identity-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  enabled: true

azureIdentity:
  enabled: true # enabled/disable deployment of azure identity and binding
  name: "azure-identity"
  type: 0 # type 0: MSI, type 1: Service Principal
  resourceID: <our MSI resourceId>
  clientID: <our clientId>

azureIdentityBinding:
  name: "azure-identity-binding"
  selector: "demo" # demo

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

```

and deployed in our aks cluster. But it does not seem to work. 

Here is the output of few commands:

```
$ kubectl get AzureIdentity --all-namespaces
NAMESPACE   NAME             AGE
default     azure-identity   7m

$ kubectl get AzureIdentityBinding --all-namespaces
NAMESPACE   NAME                     AGE
default     azure-identity-binding   7m

$ kubectl get AzureAssignedIdentities --all-namespaces
No resources found.

```

I see these errors in mic logs

```
E0313 08:38:38.810883       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/crd/crd.go:155: Failed to list *v1.AzureIdentity: unknown (get azureidentities.aadpodidentity.k8s.io)
E0313 08:38:39.420318       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/crd/crd.go:154: Failed to list *v1.AzureIdentityBinding: unknown (get azureidentitybindings.aadpodidentity.k8s.io)
```

Our cluster is rbac enabled. @kkmsft  Can please help me figure out what is going on?
