### ISSUE TITLE
Create bindings to more than one MSI

### ISSUE THREAD

**Issue by dan-jackson-github** [Azure/aad-pod-identity#183]
Hi,

Is it possible to bind a pod to more than one MSI? Do I just create an additional AzureIdentityBinding using an existing selector or can I assign more than one aadpodidbinding label ?

Thanks,

Dan

**Comment by kkmsft** [comment]
Thank you @dan-jackson-github for exploring aad-pod-identity. Right now the check in mic look at. a single label value. At this moment I don't expect it to work. 

Can you please provide a little more insights in the scenario (generic scenario) where a pod would need more than one MSI ?

**Comment by dan-jackson-github** [comment]
Hi @kkmsft, thanks for the response. I was thinking about having different MSI bindings because I was considering using different MSIs to authenticate against different Azure resources such as key vault, service bus etc. It's probably over kill but I was trying to avoid using one MSI to authenticate against multiple resources. For the time being we have just used one MSI and binding and its working well.

**Comment by kkmsft** [comment]
@dan-jackson-github - Once again, thank you for using Aad-pod-identity. If you need to created two separate identities for the same pod, then two different bindings and two different ids needs to be created. With this suggestion, closing this issue. Please feel free to reopen if anything more needs be discussed.

**Comment by xenalite** [comment]
@kkmsft Please clarify how that would look like in yaml.
I have 2 identities and 2 bindings with different label selectors. 
In my deployment, how do I set the labels to bind both identities to pods?

Deployment fragment:
```
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "modeltraining.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "modeltraining.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        aadpodidbinding: {{ .Release.Name }}-use-key-vault-reader
        aadpodidbinding: {{ .Release.Name }}-use-batch-contributor
```

When I describe the pod, only 1 label is present:
```
PS C:\Users\oskar207> kubectl describe pod -n test-2362 test-2362-modeltraining-f64fc6456-j2dp7
Name:               test-2362-modeltraining-f64fc6456-j2dp7
Namespace:          test-2362
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-42824428-1/10.240.0.4
Start Time:         Mon, 08 Jul 2019 23:52:30 +0100
Labels:             aadpodidbinding=test-2362-use-batch-contributor
                    app.kubernetes.io/instance=test-2362
                    app.kubernetes.io/name=modeltraining
                    pod-template-hash=f64fc6456
Annotations:        <none>
```

Identities, bindings and assigned identity:
```
PS C:\Users\oskar207> kubectl get azureidentity -n test-2362
NAME                          AGE
test-2362-batch-contributor   39m
test-2362-key-vault-reader    39m
PS C:\Users\oskar207> kubectl get azureidentitybinding -n test-2362
NAME                                  AGE
test-2362-batch-contributor-binding   39m
test-2362-key-vault-reader-binding    39m
PS C:\Users\oskar207> kubectl get azureassignedidentity -n test-2362
NAME                                                                                        AGE
test-2362-blobcontroller-577c5c4c8-j5nv2-test-2362-test-2362-key-vault-reader               37m
test-2362-modeltraining-f64fc6456-j2dp7-test-2362-test-2362-batch-contributor               39m
```

`test-2362-modeltraining-f64fc6456-j2dp7-test-2362-test-2362-key-vault-reader` is not assigned.
