### ISSUE TITLE
AzureIdentity with service principal does not work

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aad-pod-identity#184]
I want to use Service Principal instead of MSI, there is not any document about it yet. After checked the code, I figured out how to input the correct yaml. The type of ClientPassword is api.SecretReference, the yaml should be
```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: azurereader
spec:
  type: 1
  TenantID: xxxxxxxxxxxxxxxxxxx
  ClientID: xxxxxxxxxxxxxxxxxxx
  ClientPassword: {"Name":"azurereader","Namespace":"default"}
```
However I received `401 invalid secret` while getting token, after checked code further, I found this in
https://github.com/Azure/aad-pod-identity/blob/master/pkg/nmi/server/server.go
```
case aadpodid.ServicePrincipal:
	tenantid := v.Spec.TenantID
	logger.Infof("matched identityType:%v tenantid:%s clientid:%s", idType, tenantid, clientID)
	secret := v.Spec.ClientPassword.String()
	token, err := auth.GetServicePrincipalToken(tenantid, clientID, secret)
	return token, clientID, err
```
In my test the value of v.Spec.ClientPassword.String() is something like `&SecretReference{Name:azurereader,Namespace:default,}`, this is definitively wrong, it should pull the secret from apiserver by SecretReference instead of using the raw string.
