### ISSUE TITLE
Namespace for AzureIdentity ignored?

### ISSUE THREAD

**Issue by sarndt** [Azure/aad-pod-identity#245]
**Describe the bug**
This might not be a bug, I might be misunderstanding something, but I'm not sure.
I had an AzureIdentity created in the "default" namespace (example-identity). When I recreate this identity in the default namespace, with namespacing set to true, my Pod that is running in  another namespace (example-ns) still gets access to that identity.

**Steps To Reproduce**
*** Initial situation ***
Initial identity:
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: example-identity
spec:
  type: 0
  ResourceID: <resource ID of underlying managed identity>
  ClientId: <client ID of underlying managed identity>
```

Resource            | Namespace 
---------------- | ------------
example-identity | default
example-pod       | example-ns

*** Bug recreation ***
Everything is working nicely.
I then delete the identity:
```bash
kubectl delete azureidentity example-identity
```
Scale down the deployment that uses this identity to 0.
Recreate the identity (with namespace annotation this time):
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: example-identity
  annotations:
  - aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  ResourceID: <resource ID of underlying managed identity>
  ClientId: <client ID of underlying managed identity>
```
```bash
kubectl apply -f exampleidentity.yaml -n default
```
and scale up the Deployment again

**Expected behavior**

The Deployment should fail to get access to the identity.

**Actual behaviour**

The deployment still starts up nicely, with access to the identity.

**AAD Pod Identity version**
v1
**Kubernetes version**
1.12.7
**Additional context**

I did not recreate the AzureIdentityBinding, is this also necessary?
