### ISSUE TITLE
Why NMI need read permissions to all secrets in the cluster?

### ISSUE THREAD

**Issue by omerlh** [Azure/aad-pod-identity#248]
**Describe the request**
I looked on the [deployment manifest](https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml) and noticed that it creates a `ClusterRole` for NMI that has permissions to read all secrets in the cluster:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aad-pod-id-nmi-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureidentitybindings", "azureidentities"]
  verbs: ["get", "list"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureassignedidentities"]
  verbs: ["get", "list"]
```
This got me a bit suspicious...

**Explain why AAD Pod Identity needs it**
It looks weird to have access to all secrets in the cluster and look like giving NMI more permissions than what it needs.

**Describe the solution you'd like**
Follow least privilege principle.

**Describe alternatives you've considered**

**Additional context**
