### ISSUE TITLE
Does not work with Pod Security Policies enabled

### ISSUE THREAD

**Issue by spaelling** [Azure/aad-pod-identity#299]
Pods will not start if the cluster has Pod Security Policies enabled.

What are the recommendations to make this work with PSP?

Deploy to namespace _kube-system_?

I would prefer to deploy this to a dedicated namespace. Could you make a recommendation to a policy, role and rolebinding that works but grants nothing more than absolutely needed.

**Comment by aramase** [comment]
@spaelling This is my recommendation for a psp that can allow aad-pod-identity to work in a specific namespace -

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allow-hostnetwork
spec:
  seLinux:
    rule: RunAsAny
  privileged: true
  allowedCapabilities:
    - NET_ADMIN
  volumes:
    - '*'
  hostNetwork: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:allow-hostnetwork
  namespace: aad-pod-identity
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - allow-hostnetwork
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:allow-hostnetwork
  namespace: aad-pod-identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:allow-hostnetwork
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
```
Added it to a gist - https://gist.github.com/aramase/3c0249de86bb7833f42cc46be1c6e3df

Please try it out and let me know if you have any issues.
