### ISSUE TITLE
failed to get service principal token for pod, resource name may not be empty

### ISSUE THREAD

**Issue by tomerleib** [Azure/aad-pod-identity#464]
**Describe the bug**
On un-managed Kubernetes (deployment by Kubespray) NMI and demo pod returns the following error:
`failed to get service principal token for pod:default/demo-6d794d8764-jn48b, resource name may not be empty`
I'm testing out a deployment of Kubernetes on VMs (not AKS or AKS Engine) and 

**Steps To Reproduce**

I've created a SP for the VM's using:
```
az ad sp create-for-rbac
```
Attached it to the VM's using by running 
```
az vm identity assign -g <RESOURCE GROUP> -n <VM NAME> --identities <USER ASSIGNED IDENTITY> 
```
Populated the SP details into this manifest: https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/noazurejson/deployment-rbac.yaml
I could see that MIC is up and no errors shown there.
Created new Azure Identity, assigned it as Reader to the resource group and also assigned the clientId of the SP as Managed Identity Operator on the scope of the Azure Identity.

Created the AzureIdentity resource:
```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: demo-identity
spec:
  type: 1
  ResourceID: /subscriptions/000000000000/resourcegroups/test/providers/Microsoft.ManagedIdentity/userAssignedIdentities/k8s_pod_identity
  ClientID: 0000-1111-2222-3333-4444 (taken from the newly created Identity)
```
With the IdentityBinding and last set the label on the pod from the demo deployment.

**Expected behavior**
On AKS with MSI, the pod logs showed:
`level=info msg="succesfull doARMOperations vm count 4" podip=10.244.0.13 podname=demo-65c7ff8f67-4kdrd podnamespace=demo-65c7ff8f67-4kdrd`
I expected that it can work the same with un-managed clusters.

**AAD Pod Identity version**
1.5.4
**Kubernetes version**
1.16.3
**Additional context**
