### ISSUE TITLE
MSI bindings - get client and resource ID from secrets

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [Azure/aad-pod-identity#532]
Hi, i am wondering if there will be a way to reference client and resource ID inside an AzureIdentity from Kubernetes Secrets?

Much like the example aadpodidentity-sp.yaml for using Service Principals as seen below

Service Principal Example
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: demo-aad1-sp
type: Opaque
data:
  ClientSecret: CLIENT_SECRET
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: demo-aad1
spec:
  type: 1
  TenantID: TENANT_ID
  ClientID: CLIENT_ID
  ClientPassword: {"Name":"demo-aad1-sp","Namespace":"default"}
```

Idea for referencing values from secrets
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: demo-aad1
spec:
  type: 0
  ResourceID: {"Name":"demo-aad1-resource","Namespace":"product"}
  ClientID: {"Name":"demo-aad1-client","Namespace":"product"}
```
