### ISSUE TITLE
MIC doesn't delete user managed identities on namespace deletion

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/aad-pod-identity#533]
**Describe the bug**
As it's explained at documentation (https://github.com/Azure/aad-pod-identity#node-managed-identity), When AzureIdentity resource or all pods with this AzureIdentity assigned are deleted, MIC should automatically remove the User Managed Identity from VMSS. 

This works well if you delete directly this resources, but fails if the kubernetes namespace with this resources is deleted. MIC should notice that this resource doesn't exist anymore and should delete the user managed identity association with vmss. 

In our case, this issue is triggering this other issue: https://github.com/Azure/aad-pod-identity/issues/515. When we destroy the k8s namespace, we also delete User managed identity, but due to MIC isn't cleaning the association with the vmss, when MIC tries to create a new association, it fails in the CreateOrUpdate operation because there is an association with an unexisting user managed identity. 

**Steps To Reproduce**
1. Create a User Managed Identity
1. Create a namespace
```
kubectl create namespace test
````
1. Create an Azure Identity and an Azure Identity Binding. Azure Identity must be configured with
resource id and client id from User Managed Identity. 
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: test
  namespace: test
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  ResourceID: # From User Managed Identity
  ClientID: # From User Managed Identity
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: test
  namespace: test
spec:
  AzureIdentity: test
  Selector: test
``` 
1. Create a pod with the selector
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: test
  labels:
    app: myapp
    aadpodidbinding: test
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
```

Now you can check that user managed identity should be associated to the vmss.

1. Delete namespace
```
kubectl delete namespace test
```

User managed identity is not deleted. 
**Expected behavior**
User managed identity association with vmss should be deleted if associated k8s resources are deleted. 

**AAD Pod Identity version**
1.5.5

**Kubernetes version**
1.15.7 (AKS)

**Additional context**
We have configured aad-pod-identity with namespaced behavior.
