### ISSUE TITLE
Example of aadpodidentity using a SP. type=1

### ISSUE THREAD

**Issue by ivanthelad** [Azure/aad-pod-identity#60]
The docs state you can also use an SP as an identity. is there an example of this. my reason for the question is its not clear what should be the ResourceID.  a SP doesn't have one as far as i know. 
https://github.com/Azure/aad-pod-identity#install-user-azure-identity-on-k8s-cluster

**Comment by brent-robinson** [comment]
Has anyone come across any external documentation for this? Looks an interesting feature.

I tried without specifying a resource ID, but this fails when trying to acquire a token, e.g.

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: my-identity
spec:
 type: 1
 ClientID: ********-****-****-****-************ # this alone doesn't work
```

```
time="2019-03-23T08:14:54Z" level=info msg="matched identityType:1 tenantid: clientid:********-****-****-****-************" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.16.20
time="2019-03-23T08:14:55Z" level=error msg="failed to get service principal token for pod:default/example2-7f987b54f4-nxk7z, adal: Refresh request failed. Status Code = '404'. Response body: " req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.16.20
time="2019-03-23T08:14:55Z" level=info msg="Status (403) took 460883708 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.16.20
```
