### ISSUE TITLE
On MSI based cluster MDM metric pushing is blocked by MIC/NMI

### ISSUE THREAD

**Issue by EPinci** [Azure/aad-pod-identity#610]
**Description of the bug**

On an MSI-based AKS cluster with OMSAgent deployed per standard addon, after deploying MIC/NMI the oms daemonset pods are unable to contact the IMDS to get a token.

Behavior is shown on the /var/opt/microsoft/omsagent/log/omsagent.log of any omsagent pod.
Trying to manually CURL the IMDS form the same pod fails as well (timeout).

**Steps To Reproduce**

- Deploy an MSI-based AKS cluster with ContainerInsight integration enabled.
- Deploy MIC/NMI
- (for an easier repro, kill an omsagent pod and monitor the logs)

Note that removing the MIC/NMI deployment restores the functionality.
Note also that this issue affects just the MDM metrics, not the entire operations of the OMSAgent.

**Expected behavior**

IMDS should be contacted fine.

**AAD Pod Identity version**

v1.6.0

**Kubernetes version**

v16.7

**Additional context**

Note that this does not affect SPN based clusters

**Comment by aramase** [comment]
@EPinci can you create the following custom resource in your cluster?

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: test-exception
  namespace: <namespace in which pod identity is deployed>
spec:
  podLabels:
    app: mic
```
