### ISSUE TITLE
reuse identity for several pods

### ISSUE THREAD

**Issue by aelmanaa** [Azure/aad-pod-identity#617]
Hello,

can we reuse the same identity for different pods? 

- when I create 2 pods with the same "aadpodidbinding" , the 1st pod is able to pull the secret but the second one gets 403 errors , I get these errors without any further detail:
```
E0514 09:13:48.962744       1 server.go:228] getting assigned identities for pod kube-public/debugger-secrets-store-inline in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>
I0514 09:13:48.962824       1 server.go:190] Status (403) took 80003176432 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
```

I even tried to create different AzureIdentiy & AzureIdentityBinding for every pod without any success.

**Comment by aelmanaa** [comment]
by the way,, tried to troubleshoot . this link mentions "--v=6" https://github.com/Azure/aad-pod-identity/wiki/Debugging . However, I don't think it's updated as "nmi" expects "--debug" as argument

**Comment by aramase** [comment]
@aelmanaa This is possible today. I just tried it on my cluster and it works -

Sample AzureIdentity -

```
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: azid0
  # namespace: default
spec:
  type: 0
  resourceID: /subscriptions/<sub id>/resourcegroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/keyvault-identity
  clientID: xxxxxxxxxxxxx
```

AzureIdentityBinding -
```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azidbinding0
  # namespace: default
spec:
  azureIdentity: azid0
  selector: demo0
```

And then ran -
```
➜ kubectl run -it n0 --image=mcr.microsoft.com/azure-cli --labels "aadpodidbinding=demo0"
➜ kubectl run -it n1 --image=mcr.microsoft.com/azure-cli --labels "aadpodidbinding=demo0"
```

Both the pods, n0 and n1 have access to the same identity and the `AzureAssignedIdentity for both pods is in `ASSIGNED` state.

```
➜ kubectl get azureassignedidentity
NAME                                AGE
n0-595d79456-9p4bl-default-azid0    58s
n1-7d7787545f-9clnh-default-azid0   10s
```

```
➜ kubectl get azureassignedidentity -o jsonpath='{.items[*].status.status}'
Assigned Assigned
```

You can check the MIC logs to see why the identity isn't being assigned successfully for the pod.
