### ISSUE TITLE
Service Principal not working 

### ISSUE THREAD

**Issue by MeNsaaH** [Azure/aad-pod-identity#646]
**Describe the bug**
setting up service principal using guide in README does not work.

**Steps To Reproduce**
```
kubectl create secret generic "$IDENTITY_NAME" --from-literal=clientSecret="$CLIENT_SECRET"

echo Client ID: $CLIENT_ID

cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name:  $IDENTITY_NAME
spec:
  type: 1
  tenantID: $TENANT_ID
  resourceID: $TENANT_ID
  clientID: $CLIENT_ID
  clientPassword: {"Name":"$IDENTITY_NAME", "Namespace":"default"}
EOF

# Create an AzureIdentityBinding that reference the AzureIdentity created above 
cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: $IDENTITY_NAME-binding
spec:
  azureIdentity: $IDENTITY_NAME
  selector: $IDENTITY_NAME
EOF

```

**Expected behavior**

**AAD Pod Identity version**
Installed using Helm. 
NMI Version: 1.6.1.
**Kubernetes version**
1.18

**Additional context**
```
I0611 15:07:28.444295       1 standard.go:72] No clientID in request. default/demo has been matched with azure identity default/ccs--          
I0611 15:07:28.444375       1 standard.go:170] matched identityType:1 tenantid:XXXXXX clientid:918f##### REDACTED #####4
671 resource:https://management.azure.com/    
```
