### ISSUE TITLE
Identity not found error

### ISSUE THREAD

**Issue by greensombrero** [Azure/aad-pod-identity#69]
I have a weird situation coming up now where one of my pods can't get an identity.  It gets an error 403 error {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}

Running a kubectl get AzureAssignedIdentity I do see an identity in there however looking at the mic logs I see:

 1 crd.go:174] Got id token-issuer-identity to assign
I0727 15:49:47.694207       1 crd.go:194] Creating assigned Id: token-issuer-9fcdfdcfc-4g6dv-default-token-issuer-identity
I0727 15:49:47.928282       1 cloudprovider.go:147] Find aks-agentpool-41851317-1 in resource group: MC_dev-kitt_dev-kitt_eastus
E0727 15:49:49.137022       1 vm.go:42] compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="ResourceIdentity identityId 'XXXRedactedXXX' is not a valid reference to a Microsoft.ManagedIdentity identity." Target="resourceIdentity.identityIds"
E0727 15:49:49.137065       1 mic.go:385] compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="ResourceIdentity identityId 'XXXRedactedXXX' is not a valid reference to a Microsoft.ManagedIdentity identity." Target="resourceIdentity.identityIds"

What I don't understand though is the resource identity clearly appears when I run an az identity list.  I've copied the resource id from the id in that result and they match.  I've also confirmed the client id is the same.  Everything is set up the same for this deployment as the others where everything works except for a different Azure identity is being used.

What would cause the mic to be unable to find the identity even though I can find it?

Any suggestions on how to troubleshoot this?

Thanks!

**Comment by kkmsft** [comment]
Thanks again @greensombrero for using the pod identity and reporting back.

Assignment of the identity to the vm has failed with invalid parameter. This means that the app cannot use the identity.

Since its showing invalid parameter, can you please confirm (internally) that when you list the azureidentity and also in the logs that it is of the form (with / included):

"ResourceID": "/subscriptions/<subscripiton id>/resourcegroups/<resource group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<id name>"

A few other questions related to the scenario to get a better understanding:
1. Are you using an AKS cluster or acs-engine created cluster ?
2. Is your identity created in the same resource as that of the cluster ? (In AKS this would be the MC* group).
2. Can you please confirm that you have performed the "Assign Reader Role to new Identity" step from the README.

**Comment by khenidak** [comment]
@kkmsft maybe we should improve the error message to avoid the confusion?

**Comment by greensombrero** [comment]
So I figured this out.  I found this link https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/known-issues which mentions identities can't be longer than 24 characters or they won't be assigned.  You can create them and use them but they don't work.  We were trying to have a good naming convention to keep our identities straight as we grow and this identity as a bit too long.  We deal with that in a certain other cloud provider when you have hundreds of services with identities and multiple environments naming conventions are important.  Looks like we will have to abbreviate.  This definitely doesn't seem to be related to this specific project but do you know a place online where I might be able give some feedback I'd like to see that limit increased?

**Comment by kkmsft** [comment]
Thanks @greensombrero. Let me connect you with the right folks below.

@skwan : Can you please help @greensombrero with respect to 24 character length limitations described in the comment above.

**Comment by robinmanuelthiel** [comment]
This is a very serious issue. I ran into the same problem today and it took me **5 hours** to find this issue just to notice, that my Azure Identity Name was longer than 24 characters. Super frustrating experience, as I got 0 errors when creating or assigning the Identity...

**Comment by kkmsft** [comment]
@robinmanuelthiel : Can you please confirm that MIC logs had invalid parameter error ?
that we are in the process of adding validation via gatekeeper - PR #370 Although limitation on the identity service, we can validation to check this to get an error as soon as soon as a CRD is attempted to be created. 

@skwan : I wonder if it’s not possible to do >24 chars may be the identity creation (either on cli or portal) should error out. Thoughts ?

**Comment by robinmanuelthiel** [comment]
Well, maybe this was a false alarm. I just re-ran everything the following way and it worked, although my sp name was > 24 chars...

### Steps I took

Create a new sp and aks cluster

```bash
az ad sp create-for-rbac --skip-assignment

az aks create \
    --resource-group keyvault-test \
    --name keyvaulttestcluster \
    --node-count 1 \
    --service-principal <principalId> \
    --client-secret <principalPassword> \
    --generate-ssh-keys

az aks get-credentials --resource-group keyvault-test --name keyvaulttestcluster
```

Create an Azure Key Vault with a sample secret

```bash
az keyvault create -n keyvaulttestvault -g keyvault-test
az keyvault secret set --vault-name keyvaulttestvault --name My-Secret --value "Don't tell anyone"
```

Create a managed identity > 24 chars

```bash
az identity create -g keyvault-test -n this-is-a-very-very-long-name -o json
```

Grant permissions

```bash
az role assignment create \
    --role Reader \
    --assignee <identity-principalId> \
    --scope /subscriptions/<subscriptionId>/resourcegroups/keyvault-test

az role assignment create \
    --role "Managed Identity Operator" \
    --assignee <aksServicePrincipalClientId> \
    --scope <full-identity-id>

az keyvault set-policy \
    --name keyvaulttestvault \
    --secret-permissions list get \
    --object-id <identity-principalId>
```

Install and configure AAD Pod Identity

```bash
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
```

```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: my-identity
spec:
  type: 0
  ResourceID: <identity-id> # subscriptions/.../userAssignedIdentities/XXXX
  ClientID: <identity-clientId>
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: my-identity-binding
spec:
  AzureIdentity: my-identity
  Selector: bind-my-identity
```

Install a Demo Pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    aadpodidbinding: bind-my-identity
  name: keyvaultdemo
spec:
  containers:
    - name: keyvaultdemo
      image: robinmanuelthiel/azurekeyvaulttester:latest
      env:
        - name: AzureKeyVaultUri
          value: <keyvault-uri>
        - name: TestSecretId
          value: My-Secret
```

Check if secret can be read

```bash
kubectl logs keyvaultdemo 
#> You secret 'My-Secret' value is: Don't tell anyone
```
