### ISSUE TITLE
Cron jobs in Azure Kubernetes are not authenticating key vault using AzureIdentity (Pod Identities)

### ISSUE THREAD

**Issue by JerrySantana92** [Azure/aad-pod-identity#722]
I have a cluster in Azure AKS.

I have some pods that are fetching secrets from Key Vault, they are authenticated using MSI (Pod Identities / AzureIdentity).
Everything works as expected from the Pods!

But now I have to run some long-running tasks on schedule basis using cron Jobs.
I just realized that  cron jobs can't use the Pod Identity, how can I authenticate Key Vault then?
Do cron Jobs can use pod identities in the latest version?

Thanks!

**Comment by aramase** [comment]
@JerrySantana92 `aad-pod-identity` works for cron jobs too. Here is a sample cronjob -

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            aadpodidbinding: demo
        spec:
          containers:
            - name: hello
              image: bash
              command: ["echo",  "Hello world"]
          restartPolicy: OnFailure
```
