### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1"]

### ISSUE THREAD

**Issue by manvkaur** [Azure/aad-pod-identity#756]
**Describe the bug**
Using helm 3 to install aad pod identity to kube-system namespace
Getting below error while installing the release "aks-essentials"
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1"]

**Steps To Reproduce**
Helm Chart Templates below:
```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.identity.azureIdentity}}
spec:
  type: 0
  resourceID: {{ .Values.identity.resourceId }}
  clientID: {{ .Values.identity.clientId }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.identity.azureIdentity}}-binding
spec:
  azureIdentity: {{ .Values.identity.azureIdentity}}
  selector: {{ .Values.identity.selector}}
```

Helm Command to install the chart:

helm upgrade --namespace kube-system --install --wait --create-namespace --set identity.azureIdentity=identity-name-placeholder,identity.resourceId=resourceId-placeholder,identity.clientId=clientId-placeholder,identity.selector=identity-name-placeholder aks-essentials chart-path

**Expected behavior**
Release should get installed

**AAD Pod Identity version**
Latest

**Kubernetes version**
1.17.9

**Additional context**
Public Cluster
RBAC Enabled
With Azure CNI
