### ISSUE TITLE
Helm chart CRDs start with wrong level of 

### ISSUE THREAD

**Issue by blackbaud-james-williams** [Azure/aad-pod-identity#823]
**Have you**

- [X] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [X] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [X] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
When using Helm (v2) to install the CRDs, the first CRD starts with an extra level of indentation. 

This makes the YAML parse differently and causes the CRD installation to fail. 

**Steps To Reproduce**

In this repo: 
Run `helm template ./charts/aad-pod-identity --set=installCRDs=true | less` and examine the output. 

The first CRD document in the generated YAML will be 

```
---
# Source: aad-pod-identity/templates/crds.yaml

  apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azureassignedidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
```
Note that the `apiVersion` field is indented two spaces past the `kind` field. Kubernetes is unable to process this. 

**Expected behavior**

The first CRD document should have the `apiVersion` and `kind` fields at the same level of indentation.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
```

**AAD Pod Identity version**
1.6.3 (Helm Chart: 2.0.2)

**Kubernetes version**
N/A

**Additional context**
This is caused by the indentation in https://github.com/Azure/aad-pod-identity/blob/fb1bdba48ab5c1fa0be64382b6a74acdbcb41089/charts/aad-pod-identity/templates/crds.yaml#L3

This template should not be indented.
