### ISSUE TITLE
Fetching identity token doesn't work from pods with hostNetwork: true

### ISSUE THREAD

**Issue by nglynn** [Azure/aad-pod-identity#826]
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

Fetching identity token doesn't work from pods with hostNetwork: true

**Steps To Reproduce**

0. Assuming a working pod identity configuration with an `AzureIdentity` named "default-identity".

1. Apply this deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: repro
  name: repro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repro
  template:
    metadata:
      labels:
        aadpodidbinding: default-identity
        app: repro
    spec:
      containers:
      - args:
        - -c
        - while true; do echo hello; sleep 10;done
        command:
        - /bin/sh
        image: mcr.microsoft.com/azure-cli
        name: repro
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
```

2. Connect to the resulting pod and note:

```
bash-5.0# curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s
{"error":"invalid_request","error_description":"Identity not found"}
```

3. Edit the deployment to set `hostNetwork: false`

4. Connect to updated pod and note:

```
bash-5.0# curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s

{"access_token":"<SNIP>","refresh_token":"","expires_in":"86135","expires_on":"1602357079","not_before":"1602270379","resource":"https://management.azure.com/","token_type":"Bearer"}
```

**Expected behavior**

I hoped it would work with `hostNetwork: true`!

**AAD Pod Identity version**

1.6.3.

**Kubernetes version**

1.16.10

**Additional context**

Running on AKS.
