### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by Wema** [Azure/aad-pod-identity#876]
When following the documentation the following does not appear to be working:
https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/#performing-role-assignments

The error we kept getting was:
Message="The client '...' with object id '....' does not have authorization to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' over scope '.../providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-18386346-vmss'

It does work when we assign the roles to the AKSResourceGroup instead of the NodeResourceGroup.
Am I missing something?

**Comment by Wema** [comment]
@chewong  Just to clarify we are running into this problem in our deployment pipeline, we have it working now but we had to add the role to both resourceGroups. Below is our pipeline script this run on a newly created aks cluster:

````
- task: AzureCLI@2
    displayName: Assign roles
    inputs:
    azureSubscription: '..'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
        az role assignment create --role "Managed Identity Operator" --assignee $(clusterClientId) --scope $(aksResourceGroup)
        az role assignment create --role "Virtual Machine Contributor" --assignee $(clusterClientId) --scope $(aksResourceGroup)
        az role assignment create --role "Managed Identity Operator" --assignee $(clusterClientId) --scope $(aksNodesResourceGroup)
        az role assignment create --role "Virtual Machine Contributor" --assignee $(clusterClientId) --scope $(aksNodesResourceGroup)
        az aks update -n $(aksName) -g $(aksResourceGroup) --attach-acr $(acr)

- task: HelmInstaller@1
    displayName: Helm installer
    inputs: 
    helmVersionToInstall: latest

- script: |
    helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
    helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
    helm repo update
    displayName: Update Helm repo 

- task: HelmDeploy@0
    displayName: Deploy aad-pod-identity
    inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '..'
    azureResourceGroup: '$(aksResourceGroup)'
    kubernetesCluster: '$(aksName)'
    namespace: common-managed-identity
    command: 'upgrade'
    chartType: 'Name'
    chartName: 'aad-pod-identity/aad-pod-identity'
    waitForExecution: false
    releaseName: 'aad-pod-identity'
    arguments: '--create-namespace --atomic'
````
