### ISSUE TITLE
Make ClientId optional to enable Zero Touch deployments

### ISSUE THREAD

**Issue by Tyler-Angell** [Azure/aad-pod-identity#881]
**Describe the request**

In the UserAssignedIdentity scenario can ClientId please be made optional (or removed) so that all information when deploying to a blank resource group can be known or derived beforehand? Below is the template in question. 

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: msi-contosoapi
spec:
  type: 0
  resourceID: /subscriptions/{{ScaleUnit.Configuration.Hosting.Subscription}}/resourcegroups/{{ScaleUnit.Configuration.Hosting.ResourceGroupName}}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{Product.Configuration.Identity.Name}}
  clientID: 12345678-90ab-cdef-1234-567890abcdef # I dont have this information before deploying
```

**Explain why AAD Pod Identity needs it**
In efforts to reduce manual touch when standing up a new cluster the goal is to not have any specific IDs in the code base as each new identity that has to be copied into the templates (requiring a new build and release per company policies for touching production). Having to break a deployment into two parts to first create the IDs then to consume the IDs would be annoying, however, with the number of pod identities approaching 30 for each instance this cluster is deployed manually copying the IDs back to the template becomes a lot less fun when there are near 100 instances to maintain. 

Furthermore the UserAssignedIdentity can only have a single clientId ([source](https://docs.microsoft.com/en-us/rest/api/managedidentity/userassignedidentities/get#identityget)) so it seems redundant to specify both the resourceId and the clientId. 

**Describe the solution you'd like**
```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: msi-contosoapi
spec:
  type: 0
  resourceID: /subscriptions/{{ScaleUnit.Configuration.Hosting.Subscription}}/resourcegroups/{{ScaleUnit.Configuration.Hosting.ResourceGroupName}}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{Product.Configuration.Identity.Name}}
```
**Describe alternatives you've considered**
I'm new to kubernetes, so I'm still investigating options and open to suggestions. If there are more complex ways to inject this value I'd appreciate the pointers, but it would also be nice to reduce the barrier to entry if a more complex solution is required.
