### ISSUE TITLE
Helm chart should consider using map rather than array for "azureIdentities"

### ISSUE THREAD

**Issue by matthchr** [Azure/aad-pod-identity#885]
**Describe the request**
aad-pod-identity Helm chart currently supports something like this in `values.yaml`:
```
  azureIdentities:
    - name: aso-identity
      type: 0
      # Update values for Managed Identity
      resourceID: ""
      clientID: ""
      binding:
        name: aso-identity-binding
        selector: aso_manager_binding
```

The problem is that Helm doesn't do a great job managing arrays, as you can see discussed in this issue: https://github.com/helm/helm/issues/1987, for example it seems that when using `--set azureIdentities[0].xyz` you cannot merge the contents of `values.yaml` and `--set`. If you want to say set just a few fields of an identity (maybe the `resoruceID` and `clientID`), you actually end up having to set _all_ the properties since Helm doesn't do a nice merge.

@technosophos suggested in that same thread that you could prefer a map in these instances. That in theory should allow `--set` and `values.yaml` contents to be merged like it normally is.

**Explain why AAD Pod Identity needs it**
Would make it significantly easier to manage aad-pod-identity as a subchart, or to make use of standard `--set` and `values.yaml` merging provided by Helm.

Do note that this would be a breaking chart change I think.
