### ISSUE TITLE
Identity not found on self-managed K8S clusters and User assigned Identities

### ISSUE THREAD

**Issue by EppO** [Azure/aad-pod-identity#970]
**Have you**

- [x] Read Troubleshooting Guide. I tried https://github.com/Azure/aad-pod-identity/wiki/Debugging
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md). Didn't find that link
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
I'm running a self-managed (non AKS) cluster in Azure and use User Managed Identity. I had to specify the cloud config like below:
```
adminsecret:
    cloud: "AZUREPUBLICCLOUD"
    tenantID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
    subscriptionID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
    resourceGroup: MY-RGP
    vmType: standard
    clientID: msi
    clientSecret: msi
    useMSI: "true"
    userAssignedMSIClientID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
```
I ran into this issue: "Identity not found"
here are the [logs](https://gist.github.com/EppO/aa6184b6bab96f2cce23639f099827f6)
For some reasons, it can't get the identity, my comprehension is that it should assign the identity to the worker node VMs itself, but is there any permissions to give in order to allow the VM to use/lookup that identity?

**Steps To Reproduce**
My Identity is in the same tenant ID, subscription and resource group as the worker node VMs. It has the proper permissions on that resource group.
<img width="1123" alt="Screen Shot 2021-02-10 at 15 54 30" src="https://user-images.githubusercontent.com/6111/107572857-c8b00500-6bba-11eb-82a7-bac931e4664d.png">

**Expected behavior**
Successfully get the token for the User Managed Identity

**AAD Pod Identity version**
1.7.1

**Kubernetes version**
1.17.17

**Additional context**
I used the User Managed Client ID for the field `userAssignedMSIClientID`.
