### ISSUE TITLE
Please include an example of applying tolerations in the docs

### ISSUE THREAD

**Issue by dhirschfeld** [Azure/aad-pod-identity#975]
I'd like to deploy the AAD Pod Identity pods to my system node pool and so (IIUC) need to apply a `CriticalAddonsOnly` toleration. As a k8s noob it's not immediately obvious how to do that.

To me, the docs seem to suggest a list of strings:
https://github.com/Azure/aad-pod-identity/blob/6dc82f9d15385d23edb0898fdf4d42cdf836e541/charts/aad-pod-identity/README.md#L257

...but helm wasn't happy with that:
```
error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.tolerations[0]): invalid type for io.k8s.api.core.v1.Toleration: got "string", expected "map"
```

I think *"List of maps specifying node taints to tolerate"* would be a more accurate description. It would also be useful to have an example of what keys are expected, or a link to the docs - I assume the map should have a schema as defined in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#toleration-v1-core

**Comment by dhirschfeld** [comment]
IIUC the below config should allow the pods to be scheduled as critical pods in the `kube-system` namespace:
```yaml
mic:
  leaderElection:
    namespace: "kube-system"
  priorityClassName: "system-cluster-critical"
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"

nmi:
  micNamespace: "kube-system"
  priorityClassName: "system-cluster-critical"
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
```

Does that look right?

**Comment by chewong** [comment]
That looks good, and you can use the following command to install/upgrade?

```
helm install|upgrade ... -f values.yaml ...
```

**Comment by dhirschfeld** [comment]
I guess the pods should also have an affinity for the system node pool? If so, would that look like:
```yaml
mic:
  leaderElection:
    namespace: "kube-system"
  priorityClassName: "system-cluster-critical"
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
          matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: In
              values:
                - system
```
