### ISSUE TITLE
Add pod security policy to the helm chart

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aad-pod-identity#976]
**Describe the request**
Right now we have a pod security policy enabled in our k8s clusters that prevent the creation of certain volumes and allow only certain capabilities, etc.. this is a blocker to deploy aad-pod-identity properly so we had to create the following pod security policy for aad-pod-identity.

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: aad-pod-identity
spec:
  seLinux:
    rule: RunAsAny
  privileged: true
  allowedCapabilities:
    - NET_ADMIN
    - DAC_READ_SEARCH
    - NET_RAW
  volumes:
    - hostPath
    - secret
  hostNetwork: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-aad-pod-identity-role
  namespace: NAME
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - aad-pod-identity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-aad-pod-identity-role-binding
  namespace: NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-aad-pod-identity-role
subjects:
- kind: ServiceAccount
  name: aad-pod-identity-mic
  namespace: kube-infrastructure
- kind: ServiceAccount
  name: aad-pod-identity-nmi
  namespace: kube-infrastructure
```

**Explain why AAD Pod Identity needs it**
To deploy aad-pod-identity successfully in k8s cluster with a restricted pod-security policy enabled.

**Describe the solution you'd like**
Merge the pod security policy mentioned above in the software helm chart, and keep it updated with the new software releases.

**Describe alternatives you've considered**
the other alternative is to create the pod security policy manually, which is not good if more capabilities are needed with new sw releases and we have always to update the yaml manually (e.g. this change https://github.com/Azure/aad-pod-identity/pull/940)
